name: Secrets

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Scan
    runs-on: ubuntu-latest

    steps:
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2.3.2
